waypoint_reconfigure_config:
  version: 1.0.0
  name: "iias"
  default_dwa_limit_vel: 0.8
  default_local_inflation: 0.3
  default_global_inflation: 1.5
  areas:
    - name: "elevator1f"
      start_id: registed_0_448334000000
      end_id: registed_0_324770000000
      properties:
        - key: global_inflation
          value: 0.4
        - key: local_inflation
          value: 0.2
        - key: local_cost_cloud
          value: false
        - key: dwa_limit_vel
          value: 0.5
    - name: "elevator2f"
      start_id: registed_0_1195264000000
      end_id: registed_0_419033000000
      properties:
        - key: global_inflation
          value: 0.4
        - key: local_inflation
          value: 0.2
        - key: local_cost_cloud
          value: false
        - key: dwa_limit_vel
          value: 0.5
    - name: "auto_door1"
      start_id: registed_0_1722835210197963815
      end_id: registed_0_1722835250231555701
      properties:
        - key: global_inflation
          value: 0.4
        - key: local_inflation
          value: 0.2
        - key: local_cost_cloud
          value: false
        - key: dwa_limit_vel
          value: 0.5
    - name: "auto_door2"
      start_id: registed_0_1722835502801754747
      end_id: registed_0_1722835521288426846
      properties:
        - key: global_inflation
          value: 0.4
        - key: local_inflation
          value: 0.2
        - key: local_cost_cloud
          value: false
        - key: dwa_limit_vel
          value: 0.5
    - name: "auto_door3"
      start_id: registed_0_1722835210197963815
      end_id: registed_0_1722835250231555701
      properties:
        - key: global_inflation
          value: 0.4
        - key: local_inflation
          value: 0.2
        - key: local_cost_cloud
          value: false
        - key: dwa_limit_vel
          value: 0.5
    - name: "auto_door4"
      start_id: registed_0_1722835502801754747
      end_id: registed_0_1722835521288426846
      properties:
        - key: global_inflation
          value: 0.4
        - key: local_inflation
          value: 0.2
        - key: local_cost_cloud
          value: false
        - key: dwa_limit_vel
          value: 0.5
