waypoint_server:
  scale: 1
  position:
    x: 1
    y: 2
    z: 3
  euler_angles:
    x: 0
    y: 0
    z: 1.57000005
  waypoints:
    - id: registed_0_1763289694810931109
      position:
        x: -0.101828456
        y: -2.4531641
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57000005
    - id: 2
      position:
        x: -9.03111649
        y: -2.50835705
        z: -2.99999809
      euler_angles:
        x: -0
        y: -0
        z: 1.58006132
      properties:
        - key: stop
          value: false
        - key: goal_radius
          value: 1.0
    - id: 3
      position:
        x: 3.99999666
        y: 4.99999762
        z: 6
      euler_angles:
        x: -0
        y: 0
        z: -0
      connections:
        - 1
    - id: 1
      position:
        x: -6.00784063
        y: 4.85771799
        z: -3
      euler_angles:
        x: -0
        y: 0
        z: -0
      properties:
        - key: goal_radius
          value: 1.000000
        - key: stop
          value: true
      connections:
        - 2
